# Define the name of the Github actions/workflow.
name: Container Build Tests

# Define the Github triggers for which to launch the respective Github
# action/workflow.
on: [workflow_dispatch]

          
jobs:

  # Define the container image.
  build:
    runs-on: ubuntu-latest
    name: Run the ufs_pyutils container build tests.
        
    steps:

    # Build the Docker container containing both the Docker build as
    # well as the Singularity build.
    - name: Build and install the Linux dependencies
      run: |
           apt-get remove docker docker-engine docker.io containerd runc
           apt-get update
           apt-get install ca-certificates curl gnupg lsb-release
           mkdir -p /etc/apt/keyrings
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
           echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           chmod a+r /etc/apt/keyrings/docker.gpg
           apt-get update
           apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
           
