name: Python Coding Standards

on: [pull_request, push]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Run Python coding standards check.

  steps:
    
  - name: Build and install Python dependencies
    run: |
      wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh
      sh Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p miniconda
      python -m pip install --upgrade pip
      pip install pycodestyle

  - name: Checkout ufs_pyutils.
    uses: actions/checkout@v2
    with:
      path: ufs_pyutils

  - name: Run pycodestyle application.
    run: |
      cd $GITHUB_WORKSPACE/ufs_pyutils
      pycodestyle =v --config $GITHUB_WORKSPACE/ufs_pyutils/.pycodestyle .
     

