name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests with Python
    
    strategy:
      matrix:
        python-version: ["3.8"]
        
    steps:

    - name: Build and install Python dependencies
      run: |
        wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh
        sh Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p miniconda
        python -m pip install --upgrade pip
        pip install netcdf4
        conda install numpy
        pip install astropy
        pip install bs4
        pip install croniter
        pip install pylint
        pip install pytest==7.2.0
        conda install -c anaconda pyyaml
        conda install -c anaconda boto3

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ufs_pyutils

    - name: Run ioapps unit-tests
      run: |
        export PYTHONPATH="$GITHUB_WORKSPACE/ufs_pyutils"
        cd $GITHUB_WORKSPACE/ufs_pyutils/ioapps
        pwd
        
        #cd $GITHUB_WORKSPACE/ufs_pyutils/ufs_pyutils/ioapps
        #ls 
        #pytest 
           
#    - name: Run tools unit-tests
#      run: |
#        export PYTHONPATH="$GITHUB_WORKSPACE/ufs_pyutils"
#        cd ufs_pyutils/tools
#        pytest 
