name: Unit Tests for Package ufs_pyutils

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run ufs_pyutils unit tests.
    
    strategy:
      matrix:
        python-version: ["3.8"]
        
    steps:

    - name: Build and install Python dependencies
      run: |
        wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh
        sh Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p miniconda
        python -m pip install --upgrade pip
        pip install netcdf4
        conda install numpy
        pip install astropy
        pip install bs4
        pip install croniter
        pip install pytest==7.2.0
        pip install pytest-order
        conda install -c anaconda pyyaml
        conda install -c anaconda boto3

    - name: Checkout ufs_pyutils.
      uses: actions/checkout@v2
      with:
        path: ufs_pyutils

    - name: Run ioapps package unit-tests.
      run: |
        export PYTHONPATH="$GITHUB_WORKSPACE/ufs_pyutils"
        cd $GITHUB_WORKSPACE/ufs_pyutils/ioapps
        pytest
           
    - name: Run tools package unit-tests.
      run: |
        export PYTHONPATH="$GITHUB_WORKSPACE/ufs_pyutils"
        cd ufs_pyutils/tools
        pytest 
